### ISSUE TITLE
Teleportation chapter says can run on real device

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#119]
The teleportation circuit has gates after measurements, so it cannot be run on the currently available hardware [gives error 7006].  However, there is an entire section as the end of this chapter devoted to running on a real device.  This is exacerbated by the fact that there is a plot there that makes it look like it actually works when in fact is does not.

**Comment by dlyongemallo** [comment]
Is there a work-around or fix for this yet? I ran into the same problem on another circuit, which led me to this issue.

I tried using the classical register as the control instead, as follows:
```python
qc.measure(q[0], c[0])
qc.measure(q[1], c[1])
qc.barrier()
qc.x(q[2]).c_if(c,2)
qc.z(q[2]).c_if(c,1)
qc.x(q[2]).c_if(c,3)
qc.z(q[2]).c_if(c,3)
```

The last four lines (with `c_if`) replace these (quantumly) controlled-gates:
```python
qc.cx(q[1], q[2])
qc.cz(q[0], q[2])
```

I had to condition the control on the entire classical register (and thus was forced to duplicate the `x` and `z` gates) because apparently conditioning on single classical bits isn't supported yet (https://github.com/Qiskit/qiskit-terra/issues/1160).

(And by the way, if I don't have the `qc.barrier()` there between the `measure`s and the `c_if`s, the first `x` gate is placed before the `measure`s. Is this a bug?)

Making the above change works in the statevector and qasm simulators, however, it still results in an error on a real device:
`Instruction not in basis gates: instruction: bfunc, qubits: [], params: []. Error code: 7000.`

I'm stumped as to how to proceed.

**Comment by dlyongemallo** [comment]
Regarding my parenthetical comment about the barrier, as you can see in the following screenshots, removing it results in the classically-controlled-X gate migrating to before the result is measured into the classical register. A `c_if` should obviously not commute with a `measure` that affects the control.

![with barrier](https://user-images.githubusercontent.com/9248532/71639801-bc4e3e80-2c7d-11ea-9271-d23a5445db0b.png)
![without barrier](https://user-images.githubusercontent.com/9248532/71639803-c6703d00-2c7d-11ea-90a7-5368537c45df.png)

**Comment by dlyongemallo** [comment]
I discovered @quantumjim's [trick to split up the classical register](https://quantumcomputing.stackexchange.com/questions/4260/how-to-create-a-condition-on-only-one-classical-bit-when-we-have-a-total-of-2-cl) so this code can be replaced:

```python
qc.x(q[2]).c_if(c,2)
qc.z(q[2]).c_if(c,1)
qc.x(q[2]).c_if(c,3)
qc.z(q[2]).c_if(c,3)
```

with:

```python
circuit.x(q[2]).c_if(c[1],1)
circuit.z(q[2]).c_if(c[0],1)
```

But in any case, the underlying problem of getting error code 7000 remains and I'm unable to fix the teleport code.

**Comment by aasfaw** [comment]
Hey @dlyongemallo, this has been fixed in the latest version of the teleporation chapter. The issue arose because measurement-conditioned gates are currently not supported on the real devices.
