### ISSUE TITLE
textbook link next does not work 

### ISSUE THREAD

**Issue by Ayshine** [Qiskit/qiskit-textbook#128]
The next button on the **Introduction to Python and Jupyter notebooks** page
https://qiskit.org/textbook/ch-prerequisites/python-and-jupyter-notebooks.html
supposed to redirect to  **qiskit**
https://qiskit.org/textbook/ch-prerequisites/qiskit.html 
page but it stays on the same html file.

**Comment by schwarmco** [comment]
I think, i found the issue here.

It happens on all first sub-sections. (ex.: https://qiskit.org/textbook/ch-ex/ex1.html or https://qiskit.org/textbook/ch-states/introduction.html).

The problem is in how jupyter-book finds the "current page" in the toc.yml. As both, the Section-Heading (ex. "Prerequisites") as well as the first sub-section (ex.: "Python and Jupyter Notebooks") having the same url (/ch-prerequisites/python-and-jupyter-notebooks), jupyter-book finds the Section-Heading as "current-page" and links to idx+1 (the first subsection).

I hope, i've explained this somewhat undestanable. The relevant code sections are here:

https://github.com/Qiskit/qiskit-textbook/blob/5bd57d8bac4e90a81e5bee804fc9aa8f796dc526/_data/toc.yml#L36-L43

https://github.com/jupyter/jupyter-book/blob/797d29ac042c7cd3c8b830b4a04775ec5874df65/jupyter_book/build.py#L231

A possible (but a little hacky) solution, would be to flag the Section-Headings as "external", which would jupyter-book ignore them in calculating.

Another approach would be, to create index-pages instead of linking to the first sub-section (ex. /textbook/ch-prerequisites). This would also resolve the (very minor) issue, of having a 404 sitting at these directories (ex. https://qiskit.org/textbook/ch-states/)
