### ISSUE TITLE
3.6QFT convention changing in explanation and programm code

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#287]
![QFT_CROT](https://user-images.githubusercontent.com/43704364/77832174-51a18780-7134-11ea-9a79-ac70fb19c5cb.jpg)
## Describe the Issue
In the chapter 3.6 QFT in step 5 the explanation chooses the right image.
Of course both are equivalent, but changing the numbering of qubits (starting at 0 and also flipping the whole circuit is disturbing for understanding (especially when mentioning the inverted output after QFT, so one my think mirroring the circuit could already counteract that).
## Expected Solution
As it is easier to program the general QFT like in the left image, this circuit convention should be used in the first place when explaining the QFT in step 5.
## Anything else we should know?
If you change the picture as suggested the examples in step 6 need to be 
adjusted too.

**Comment by frankharkins** [comment]
The problem is that qiskit's least significant qubit has the lowest index, but in most textbooks the QFT looks like the one on the right. I think using both conventions are fine as long as it's clearly explained why we switch in section 8. There is a short sentence aknowledging this but maybe it needs to be emphasised a bit more?
