### ISSUE TITLE
4.1.1hhl 4B circuit doesn't run on real devices

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#309]
## Describe the Issue
There are multiple errors due to changed qiskit functions, but also due to missing definition of constants. It is hard to guess which values they have as the optimized circuit is not explained in the chapter and I couln't find the reference 5.
![hhl_4B_load_accounts](https://user-images.githubusercontent.com/43704364/78182436-782e2e00-7466-11ea-810c-31dd4f0bd600.png)

It is not clear how to derive t or C for the algorithm and also m is appearing in the optimized version.
![hhl_4B_t_m](https://user-images.githubusercontent.com/43704364/78183922-f8559300-7468-11ea-9dae-f09e585d13bb.png)

![hhl_4B_t_not_defined](https://user-images.githubusercontent.com/43704364/78182462-8714e080-7466-11ea-8738-b7d9fab9d497.png)

## Expected Solution
Use new qiskit methods.
Define constants and save results of job and plot them.
## Anything else we should know?
I think the authors do not attempt to show the Richard extrapolation here (as it is to extensive?)
I will start with interchanging for new qiskit functions, but will need help to get the right constants.

**Comment by anedumla** [comment]
Hi,

Choosing the time parameter was meant as an exercise that never got explicitly added (so thanks for pointing this out), it will soon be included into the Problems section with the right solution and a hint. 

Regarding Richardson extrapolation, you are right in the sense that it was not included with a full explanation since it would have made the section too long and would have deviated from the main topic, i.e. the HHL. However, an outline of the process is included in 4B for those that were interested, which together with exercise 3 (4 after the update) should be enough to get an idea of how to apply it.
