### ISSUE TITLE
4.1.1hhl 2C QPE should give |2^n * eigenvalue>?

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#311]
## Describe the Issue
In chapter for QPE for U = e^(2 pi theta i) gives |2^n * theta> as result.
Now for U = e^(lambda t i) I would assume |2^n *  lambda *( t / 2pi)> as result, but in the textbook just |lambda> is stated.
![hhl_2C_2**n_theta](https://user-images.githubusercontent.com/43704364/78188541-b6304f80-7470-11ea-9611-70b9f3906aa7.png)

## Expected Solution
Solve the misunderstanding.

**Comment by anedumla** [comment]
The reason it returns |lambda> is because the 2pi factor has already been included in the Hamiltonian simulation (as highlighted below), so the result is already simplified:
![image](https://user-images.githubusercontent.com/5624856/79586350-46a59b80-80d1-11ea-84ea-2744d9926fd3.png)

QPE can only estimate the first 'n' digits after the decimal point of theta, i.e. if theta = 12.125, QPE returns a binary approximation to 0.125. For n=4 this would be 0010, which if you read as an integer number then 0010 is 2 = (2^4)*0.125, but if you read it as the binary representation of a decimal number then 0010 is 0.125. So what I am trying to say is that it is mostly a matter of how you prefer to read it.

I will update the tutorial to make this point clearer, thanks for your input!

**Comment by HTransistor** [comment]
> Now for U = e^(lambda t i) I would assume |2^n * lambda *( t / 2pi)> as result, but in the textbook just |lambda> is stated.

Okay then t=2pi, so the result should be |2^n lambda>.

In your example I would write dual 0.0010 = 2^(-3) = 1/8 = 0.125 decimal (first 0.  to make clear we work with fractionals of the dual system, so after the decimal you read from left to right for ).

![fractions](https://user-images.githubusercontent.com/43704364/79630066-b312b000-814e-11ea-8aad-05f01bda364d.png)

![fractions_formula](https://user-images.githubusercontent.com/43704364/79630061-aaba7500-814e-11ea-9368-e70495c5944a.png)

So your point is that, there is a 2^n * lambda, but you are using a different notation, right?

**Comment by anedumla** [comment]
Exactly, but it will be made consistent with the other chapters to avoid confusion.
