### ISSUE TITLE
set default draw to mpl

### ISSUE THREAD

**Issue by aasfaw** [Qiskit/qiskit-textbook#327]
## Describe the Issue
The default method for drawing circuits using `my_circuit.draw()` should be matplotlib instead of text.
Instead, we now specify the argument `output='mpl'`. 

## Expected Solution
Set up the config file as explained here so that the default drawer is matplotlib.
https://qiskit.org/documentation/getting_started.html#step-4-visualize-the-circuit

**Comment by frankharkins** [comment]
I have a couple of reservations about this:
1. If the reader can't see our config then they might not understand why they are seeing text drawings and the textbook is displaying mpl drawings. Could potentially fix this by explaining in the prereq section but not every reader will go through that.
2. Due to bugs in qiskit/mpl some gates do not render correctly with mpl (mainly the `initialize` gate) so we have reverted to text drawings for these
