### ISSUE TITLE
Links to .ipynb instead of .html for running locally

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-textbook#77]
In the `index.ipynb`, links to chapters have `.html` suffix, instead of `.ipynb`, which gives 404 errors when running locally and on Github. However it is working perfectly on https://community.qiskit.org/textbook/. Why is that? Do Github pages automatically generatre html pages for each ipynb file?

It would be also nice if the textbook can be interactive online, similar to the qiskit tutorials (https://quantum-computing.ibm.com/jupyter/tutorial/fundamentals/1_getting_started_with_qiskit.ipynb)

**Comment by HuangJunye** [comment]
Perhaps you are the best person to ask for the question @1ucian0

**Comment by aasfaw** [comment]
Great idea @HuangJunye -- we'll update the index to point to ipynbs. As you've guessed, the htmls are autogenerated, and that's why this fails locally. We are updating to jupyterbook, which gets around this issue. Jupyterbook also gives you interactivity via navigation buttons and search. Integration with the IBM Q Experience is coming up next 👍

**Comment by HuangJunye** [comment]
@aasfaw Jupyterbook looks really nice. It’s a good direction to go! Look forward to the IQX integration :)

**Comment by schwarmco** [comment]
As we're using jupyterbook and the notebooks are linked correctly in both places now, this issue can be closed :)
